package y2025.day07

import io.kotest.matchers.shouldBe
import kotlin.test.Test
import y2025.day07.Day07.Companion.bottomUp
import y2025.day07.Day07.Companion.countBranches
import y2025.day07.Day07.Companion.topDown

class Y2025Day07Test {

    val exampleInput =
"""
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
"""


    @Test
    fun day7Test() {

        val wiredTree = exampleInput.lines().filter { it.isNotBlank() }.topDown()

        // example p1
        wiredTree.countBranches() shouldBe 21

        // example p2
        wiredTree.bottomUp() shouldBe 40
    }
}